project/proj/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from proj import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/filebrowser/', include('filebrowser.urls')),
    url(r'^admin_tools/',       include('admin_tools.urls')),
    url(r'^admin/doc/',         include('django.contrib.admindocs.urls')),
    url(r'^admin/',             include(admin.site.urls)),
    url(r'^tinymce/',           include('tinymce.urls')),
    url(r'^$',                  'main_pages.views.pagesview'),
    url(r'^gallery_main/$',     'main_gall.views.gallery_view', name='gallery'),
    url(r'^news_list/$',        'main_pages.views.news_list_view', name='news_list'),
    url(r'^news/(?P<pk>\d+)/$', 'main_pages.views.newsview'),
    url(r'^send_mail/$',        'main_pages.views.contactview', name='contact_mail'),
    url(r'^success/$',          'main_pages.views.success_view', name='success'),
    url(r'^(?P<url>.+)/$',      'main_pages.views.pagesview'),
)



if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            }),
    )

project/gallery/models.py
from django.db import models
from main_pages.models import ChildPages, News


class Gallery(models.Model):
	"""
	model for gallery for dop. pages
	"""
	parent = models.ForeignKey(ChildPages, related_name='rel_gallery_parent')
	img = models.ImageField(upload_to='images')

	def __unicode__(self):
		return u'%s' % (self.id,)


class News(models.Model):
	"""
	model for gallery for dop. pages
	"""
	parent = models.ForeignKey(News, related_name='rel_news_parent')
	img = models.ImageField(upload_to='images')

	def __unicode__(self):
		return u'%s' % (self.id,)

project/slider/models.py
# -*- coding:utf-8 -*-

from django.db import models
from main_pages.models import Pages, ChildPages


class SliderImgs(models.Model):
    """
    model for imgages slider
    """
    main_page  = models.ForeignKey(Pages, verbose_name=u'Отображение на основной странице', related_name='rel_main_page_slider', null=True, blank=True)
    child_page = models.ForeignKey(ChildPages, verbose_name=u'Отображение на доп. страницах', related_name='rel_child_page_slider', null=True, blank=True)
    for_all    = models.BooleanField(u'Отобразить на всех страницах', default=True)
    active     = models.BooleanField(u'Активность', default=True)
    img        = models.ImageField(u'Картинка', upload_to='images')
    desc       = models.CharField(u'Описание', max_length=150, blank=True)
    alt        = models.CharField(u'Описание если не доступна',max_length=100)

    def __unicode__(self):
        return self.alt

    class Meta:
        verbose_name = u'Картинка для слайдера'
        verbose_name_plural = u'Картинки для слайдера'

project/gallery/views.py
# Create your views here.

project/proj/templates/child.html
{% extends 'base.html' %}

{% block title %}
    {{ page.title }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="span10 offset1">
             <h1>{{ page.title }}</h1>
             {{ page.body|safe }}
        </div>
	{% if page.rel_gallery_parent.all %}
		<div class="span10 offset1">
			<div id='gallery' class='gallery-set'>
				<ul>
			{% for item in page.rel_gallery_parent.all %}
					<li>
					<a href='{{ item.img.url }}'>
						<img src='{{ item.img.url }}' width='100'>
					</a>
					</li>
			{% endfor %}
				</ul>
			</div>
		</div>
	{% endif %}
    </div>
{% endblock %}

project/proj/templates/contact.html
{% extends 'base.html' %}

{% block title %}
    Написать нам
{% endblock %}

{% block content %}
    <div class="row">
        <div class="span10 offset1">
            <h1>Напишите нам письмо</h1>
            <div class='form_div'>
                <form class="form-horizontal" action="" method="POST">{% csrf_token %}
                    {% include 'form_template.html' with form=form %}
                    <div class="control-group">
                        <div class="controls">
                            <button type="submit" class="btn btn-primary">Отправить</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

project/proj/templates/footer.html
<div class="row">
    <div class="span3 blue">
        &copy; Времена Года.<br>
        Интерьерная мастерская
    </div>
    <div class="span3 yellow">
        {{ address }}<br>
        {{ metro }}
    </div>
    <div class="span3 blue" style='text-align:right;'>
        {{ telefon }}<br>
        {{ email }}
    </div>
    <div class="span3 green align_right">
        <a href="#">Разработка сайта</a>
    </div>
</div>

project/proj/templates/form_template.html
{% for hidden in form.hidden_fields %}
    {{ hidden }}
{% endfor %}
{% for field in form %}
    <div class="control-group
        {% if field.errors %}
            error
        {% endif %}
        ">
        <label class="control-label" for="id_{{ field.name }}">{{ field.label }}:</label>
        <div class="controls">
            {{ field }}
            {% if field.errors %}
                <span class="help-inline">
                        {% for error in field.errors %}
                            <strong>{{ error|escape }}</strong><br>
                        {% endfor %}
                    </span>
            {% endif %}
        </div>
    </div>
{% endfor %}

project/proj/templates/gallery.html
{% extends 'base.html' %}

{% block title %}
Галерея
{% endblock %}

{% block script_top %}
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-1.3.2.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.galleriffic.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.opacityrollover.js"></script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="span10 offset1">
        <div id="controls"></div>
        <div id="loading"></div>
        <div id="slideshow"></div>
        <div id="caption"></div>
        <div id="thumbs">
            <ul class="thumbs noscript">
            {% for item in gallery_set %}
                <li>
                    <a class="thumb" name="{{ item.name }}" href="{{ item.img.url }}" title="{{ item.title }}">
                        <img width="75" height='75' src="{{ item.thumb.url }}" alt="{{ item.alt }}" />
                    </a>
                    <div class="caption">
                        <p>
                            {{ item.caption }}
                        </p>
                    </div>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
</div>
<script type="text/javascript">
            jQuery(document).ready(function($) {
                            // We only want these styles applied when javascript is enabled
                            $('div.navigation').css({'width' : '300px', 'float' : 'left'});
                            $('div.content').css('display', 'block');
                            // Initially set opacity on thumbs and add
                            // additional styling for hover effect on thumbs
                            var onMouseOutOpacity = 0.67;
                            $('#thumbs ul.thumbs li').opacityrollover({
                            mouseOutOpacity:   onMouseOutOpacity,
                            mouseOverOpacity:  1.0,
                            fadeSpeed:         'fast',
                            exemptionSelector: '.selected'
                            });
                            
                           // Initialize Advanced Galleriffic Gallery
                           var gallery = $('#thumbs').galleriffic({
                           delay:                     2500,
                           numThumbs:                 15,
                           preloadAhead:              10,
                           enableTopPager:            true,
                           enableBottomPager:         true,
                           maxPagesToShow:            7,
                           imageContainerSel:         '#slideshow',
                           controlsContainerSel:      '#controls',
                           captionContainerSel:       '#caption',
                           loadingContainerSel:       '#loading',
                           renderSSControls:          true,
                           renderNavControls:         true,
                           playLinkText:              'Play Slideshow',
                           pauseLinkText:             'Pause Slideshow',
                           prevLinkText:              '&lsaquo; Previous Photo',
                           nextLinkText:              'Next Photo &rsaquo;',
                           nextPageLinkText:          'Next &rsaquo;',
                           prevPageLinkText:          '&lsaquo; Prev',
                           enableHistory:             false,
                           autoStart:                 false,
                           syncTransitions:           true,
                           defaultTransitionDuration: 900,
                           onSlideChange:             function(prevIndex, nextIndex) {
                           // 'this' refers to the gallery, which is an extension of $('#thumbs')
                           this.find('ul.thumbs').children()
                           .eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
                           .eq(nextIndex).fadeTo('fast', 1.0);
                           },
                           onPageTransitionOut:       function(callback) {
                           this.fadeTo('fast', 0.0, callback);
                           },
                           onPageTransitionIn:        function() {
                           this.fadeTo('fast', 1.0);
                           }
                           });
                           });
                           </script>
{% endblock %}

project/proj/templates/gallery2.html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>Галерея | Времена года</title>


    <link rel="stylesheet" href="{{ MEDIA_URL }}css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/style.css">


		<link rel="stylesheet" href="{{ MEDIA_URL }}css/basic.css" type="text/css" />
		<link rel="stylesheet" href="{{ MEDIA_URL }}css/galleriffic-2.css" type="text/css" />
		<!-- <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-1.3.2.js"></script> -->
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.min.js"></script>

    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.nivo.slider.pack.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.lightbox-0.5.pack.js"></script>
    <link rel="stylesheet" href="{{ MEDIA_URL }}themes/default/default.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/nivo-slider.css" type="text/css" media="screen" />
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/jquery.lightbox-0.5.css" media="screen" />

    <script type="text/javascript">
        $(window).load(function() {
            $('#slider').nivoSlider({
	    	pauseTime: 6000,
	    });
        });
       $(function() {
        $('#gallery a').lightBox({
	imageLoading: '{{ MEDIA_URL }}images/lightbox-ico-loading.gif',
	imageBtnClose: '{{ MEDIA_URL }}images/lightbox-btn-close.gif',
	imageBtnPrev: '{{ MEDIA_URL }}images/lightbox-btn-prev.gif',
	imageBtnNext: '{{ MEDIA_URL }}images/lightbox-btn-next.gif',
	imageBlank: '{{ MEDIA_URL }}images/lightbox-blank.gif'
	});
       });
    </script>


		<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.galleriffic.js"></script>
		<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.opacityrollover.js"></script>
		<!-- We only want the thunbnails to display when javascript is disabled -->
		<script type="text/javascript">
			document.write('<style>.noscript { display: none; }</style>');
		</script>
	</head>
	<body>



<div id='mywropper' class='container'>
    <div id="header">
        <div class="row">
            <div class='span5 blue'>
                <a href="/" id='logo'>Времена года - мастерская инрерьерных решений</a>
            </div>
            {% include 'menu.html' %}
        </div>
        <div class="row">
            <div class="span12">
                {% include 'slider.html' %}
            </div>
        </div>
        <div class="line"></div>
    </div>
    <div id="main">

<div class="row">
    <div class="span10 offset1">


		<div id="page">
			<div id="container">
				<h1 class='margin-bot'>Наши работы</h1>

				<!-- Start Advanced Gallery Html Containers -->
				<div id="gallery" class="content">
					<div id="controls" class="controls"></div>
					<div class="slideshow-container">
						<div id="loading" class="loader"></div>
						<div id="slideshow" class="slideshow"></div>
					</div>
					<div id="caption" class="caption-container"></div>
				</div>
				<div id="thumbs" class="navigation">
					<ul class="thumbs noscript">
            {% for item in gallery_set %}
						<li>
							<a class="thumb" name="{{ item.name }}" href="{{ item.img.url }}" title="{{ item.title }}">
								<img src="{{ item.thumb.url }}" alt="{{ item.alt }}" />
							</a>
							<div class="caption">
								<!--<div class="download">
									<a href="http://farm4.static.flickr.com/3261/2538183196_8baf9a8015_b.jpg">Download Original</a>
								</div>-->
								<div class="image-title">{{ item.title }}</div>
								<div class="image-desc">{{ item.alt }}</div>
							</div>
						</li>
            {% endfor %}
					</ul>
				</div>
				<div style="clear: both;"></div>
			</div>
		</div>
		<!-- <div id="footer">&copy; 2009 Trent Foley</div> -->
		<script type="text/javascript">
			jQuery(document).ready(function($) {
				// We only want these styles applied when javascript is enabled
				$('div.navigation').css({'width' : '300px', 'float' : 'left'});
				$('div.content').css('display', 'block');

				// Initially set opacity on thumbs and add
				// additional styling for hover effect on thumbs
				var onMouseOutOpacity = 0.67;
				$('#thumbs ul.thumbs li').opacityrollover({
					mouseOutOpacity:   onMouseOutOpacity,
					mouseOverOpacity:  1.0,
					fadeSpeed:         'fast',
					exemptionSelector: '.selected'
				});
				
				// Initialize Advanced Galleriffic Gallery
				var gallery = $('#thumbs').galleriffic({
					delay:                     2500,
					numThumbs:                 15,
					preloadAhead:              10,
					enableTopPager:            true,
					enableBottomPager:         true,
					maxPagesToShow:            7,
					imageContainerSel:         '#slideshow',
					controlsContainerSel:      '#controls',
					captionContainerSel:       '#caption',
					loadingContainerSel:       '#loading',
					renderSSControls:          true,
					renderNavControls:         true,
					playLinkText:              'Запустить слайдшоу',
					pauseLinkText:             'Остановить слайдшоу',
					prevLinkText:              '&lsaquo; Предыдущее',
					nextLinkText:              'Следующее &rsaquo;',
					nextPageLinkText:          'Далее &rsaquo;',
					prevPageLinkText:          '&lsaquo; Назад',
					enableHistory:             false,
					autoStart:                 false,
					syncTransitions:           true,
					defaultTransitionDuration: 900,
					onSlideChange:             function(prevIndex, nextIndex) {
						// 'this' refers to the gallery, which is an extension of $('#thumbs')
						this.find('ul.thumbs').children()
							.eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
							.eq(nextIndex).fadeTo('fast', 1.0);
					},
					onPageTransitionOut:       function(callback) {
						this.fadeTo('fast', 0.0, callback);
					},
					onPageTransitionIn:        function() {
						this.fadeTo('fast', 1.0);
					}
				});
			});
		</script>


    </div>
</div>
        <div class="line"></div>
    </div>
    <div id="footer">
        {% include 'footer.html' %}
    </div>
</div>




	</body>
</html>

project/proj/templates/gallery_base.html
<!DOCTYPE html>
<html>
<head>
    <title>Галерея | Времена года</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/style.css">
    <link rel="stylesheet" href="{{ MEDIA_URL }}themes/default/default.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/nivo-slider.css" type="text/css" media="screen" />
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/jquery.lightbox-0.5.css" media="screen" />
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/basic.css" type="text/css" />
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/galleriffic-2.css" type="text/css" />
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-1.3.2.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.galleriffic.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.opacityrollover.js"></script>
    <script type="text/javascript">
        document.write('<style>.noscript { display: none; }</style>');
   </script>
</head>
<body>
<div id='mywropper' class='container'>
    <div id="header">
        <div class="row">
            <div class='span5 blue'>
                <a href="/" id='logo'>Времена года - мастерская инрерьерных решений</a>
            </div>
            {% include 'menu.html' %}
        </div>
        <div class="row">
            <div class="span12">
            </div>
        </div>
        <div class="line"></div>
    </div>
    <div id="main">

<div class="row">
    <div class="span10 offset1">
        <div id="controls"></div>
        <div id="loading"></div>
        <div id="slideshow"></div>
        <div id="caption"></div>
        <div id="thumbs">
            <ul class="thumbs noscript">
            {% for item in gallery_set %}
                <li>
                    <a class="thumb" name="{{ item.name }}" href="{{ item.img.url }}" title="{{ item.title }}">
                        <img width="75" height='75' src="{{ item.thumb.url }}" alt="{{ item.alt }}" />
                    </a>
                    <div class="caption">
                        <p>
                            {{ item.caption }}
                        </p>
                    </div>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
</div>
<script type="text/javascript">
            jQuery(document).ready(function($) {
                            // We only want these styles applied when javascript is enabled
                            $('div.navigation').css({'width' : '300px', 'float' : 'left'});
                            $('div.content').css('display', 'block');
                            // Initially set opacity on thumbs and add
                            // additional styling for hover effect on thumbs
                            var onMouseOutOpacity = 0.67;
                            $('#thumbs ul.thumbs li').opacityrollover({
                            mouseOutOpacity:   onMouseOutOpacity,
                            mouseOverOpacity:  1.0,
                            fadeSpeed:         'fast',
                            exemptionSelector: '.selected'
                            });
                            
                           // Initialize Advanced Galleriffic Gallery
                           var gallery = $('#thumbs').galleriffic({
                           delay:                     2500,
                           numThumbs:                 15,
                           preloadAhead:              10,
                           enableTopPager:            true,
                           enableBottomPager:         true,
                           maxPagesToShow:            7,
                           imageContainerSel:         '#slideshow',
                           controlsContainerSel:      '#controls',
                           captionContainerSel:       '#caption',
                           loadingContainerSel:       '#loading',
                           renderSSControls:          true,
                           renderNavControls:         true,
                           playLinkText:              'Play Slideshow',
                           pauseLinkText:             'Pause Slideshow',
                           prevLinkText:              '&lsaquo; Previous Photo',
                           nextLinkText:              'Next Photo &rsaquo;',
                           nextPageLinkText:          'Next &rsaquo;',
                           prevPageLinkText:          '&lsaquo; Prev',
                           enableHistory:             false,
                           autoStart:                 false,
                           syncTransitions:           true,
                           defaultTransitionDuration: 900,
                           onSlideChange:             function(prevIndex, nextIndex) {
                           // 'this' refers to the gallery, which is an extension of $('#thumbs')
                           this.find('ul.thumbs').children()
                           .eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
                           .eq(nextIndex).fadeTo('fast', 1.0);
                           },
                           onPageTransitionOut:       function(callback) {
                           this.fadeTo('fast', 0.0, callback);
                           },
                           onPageTransitionIn:        function() {
                           this.fadeTo('fast', 1.0);
                           }
                           });
                           });
                           </script>
        <div class="line"></div>
    </div>
    <div id="footer">
        {% include 'footer.html' %}
    </div>
</div>
</body>
</html>

project/proj/templates/main.html
{% extends 'base.html' %}

{% block title %}
    Главная
{% endblock %}

{% block content %}
    <div class="row">
        {% include 'main_page_menu.html' %}
        <div class="span7 green">
            {# {% include 'main_imgs.html' %} #}
            <div class="row">
                <div class="span7 contant">
                    <h1>{{ page.title }}</h1>
                    {{ page.body|safe }}
                </div>
            </div>
        </div>
        <div class="span2 blue right_bar">
            {% include 'news.html' %}
        </div>
    </div>
{% endblock %}

project/proj/templates/main_imgs.html
<div class="row">
    {% for item in main_page_3_imgs %}
        <div class="span2">
            <img src="{{ item.img.url }}" alt="{{ item.title }}" width="140" height="89">
            <a href="/{{ item.page.url }}">{{ item.page.title }}</a>
            <p>{{ item.title }}</p>
        </div>
    {% endfor %}
</div>

project/proj/templates/main_page_menu.html
<div class="span3 blue">
    <ul class='left_side_menu'>
        {% for item in main_page_menu_items %}
            <li><a href="/{{ item.url }}/">{{ item.menu_title }}</a></li>
        {% endfor %}
    </ul>
</div>

project/proj/templates/menu.html
<div class='span5 green padding_menu'>
    <div class="menu_wrop">
        <ul class='menu'>
            {% for item in menu_items %}
                <li>
                    {% if item.url == 'main' %}
                    <a href="/">{{ item.menu_title }}</a>
                    {% else %}
                    <a href="/{{ item.url }}/">{{ item.menu_title }}</a>
                    {% endif %}
                    {% if item.rel_childs.all %}
                        <ul class='hide'>
                            {% for child in item.rel_childs.all %}
                                {% if child.menu_active %}
                                    <li><a href="/{{ child.url }}/">{{ child.menu_title }}</a></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
<div class="span2 padding_menu">
    <div class="menu_mail align_right">
        <a href="{% url contact_mail %}">Написать нам</a>
    </div>
</div>

project/proj/templates/news_list.html
{% extends 'base.html' %}

{% block title %}
    Список новостей
{% endblock %}

{% block content %}
    <div class="row">
        <div class="span10 offset1">
            <h1>Список всех новостей</h1>
            {% for item in news_list %}
                {% if item.active %}
                    <div class='row'>
                        <div class='span12'>
                            <h2><a href="/news/{{ item.id }}/">{{ item.title }}</a></h2>
                            <p>{{ item.date }}</p>
                            {# <div>{{ item.body|truncatewords:10 }}</div> #}
                        </div>
                    </div>
                    <br>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

project/proj/templates/one_new.html
{% extends 'base.html' %}

{% block title %}
    {{ page.title }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="span10 offset1">
            <h1>{{ page.title }}</h1>
            <p>{{ page.date }}</p>
            {{ page.body|safe }}
        </div>
{% if page.rel_news_parent.all %}
		<div class="span10 offset1">
			<div id='gallery' class='gallery-set'>
				<ul>
			{% for item in page.rel_news_parent.all %}
					<li>
					<a href='{{ item.img.url }}'>
						<img src='{{ item.img.url }}' width='100'>
					</a>
					</li>
			{% endfor %}
				</ul>
			</div>
		</div>
	{% endif %}
    </div>
{% endblock %}

project/proj/templates/success.html
{% extends 'base.html' %}

{% block title %}
    Спасибо
{% endblock %}

{% block content %}
    <div class="row">
        <div class="span10 offset1">
            <h1>Ваше письмо отправлено спасибо</h1>
        </div>
    </div>
{% endblock %}